### ISSUE TITLE
Unstable library feature 'build_hasher_simple_hash_one'

### ISSUE THREAD

**Issue by Tartopoms** [ealmloff/sledgehammer_utils#2]
Hello there,

I'm using `rustc 1.70.0` and `rustup 1.26.0`.

I'm working on a project using Dioxus Rust framework.
`sledgehammer_utils` is a dependency of `dioxus-interpreter-js v0.4.3`.
The sledgehammer has been updated from `0.2.0` to `0.2.1`.

When I run my Dioxus project with `dx serve --hot-reload`, I get the following error:
```rs
[INFO] 🚅 Running build command...
Error: 🚫 Serving project failed: error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
   --> /root/.cargo/registry/src/custom-registry/sledgehammer_utils-0.2.1/src/lib.rs:124:32
    |
124 |         let hash = self.hasher.hash_one(&val);
    |                                ^^^^^^^^
    |
    = note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information


error: Broken pipe (os error 32)
error: could not compile `sledgehammer_utils` (lib) due to 2 previous errors
```

This error raised by the `#![feature(build_hasher_simple_hash_one)]` flag (see this [issue](https://github.com/rust-lang/rust/issues/86161)) prevents me from compiling my project.

**Comment by ealmloff** [comment]
`hash_one` was stabilized in rust `1.71` updating your rust version should fix the error
